spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    add-properties: true
  jpa:
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SGI
          jwk-set-uri: http://localhost:8080/realms/SGI/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9090

keycloak:
  realm: SGI
  resource: sgi-client
  auth-server-url: http://localhost:8080/auth/
  ssl-required: none
  public-client: true
  principal-attribute: preferred_username
  cors: true
